"""
Candidate Answer Evaluation (Embeddings + Cosine Similarity)
===========================================================

Implements `answer_evaluator.py` from your target architecture.

Approach:
- For each interview question, obtain an "ideal answer" (can be generated by local LLM)
- Embed candidate answer + ideal answer using sentence-transformers
- Compute cosine similarity
- Convert similarity to a 0–100 score
- Provide short feedback text

This is a lightweight baseline. You can later upgrade to rubric-based grading.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Dict, List, Optional, Sequence, Tuple

import numpy as np
from typing import Protocol
from sklearn.feature_extraction.text import TfidfVectorizer


@dataclass(frozen=True)
class EvaluationResult:
    score: int  # 0..100
    similarity: float  # 0..1
    feedback: str
    ideal_answer: str

    def to_dict(self) -> Dict[str, Any]:
        return {
            "score": int(self.score),
            "similarity": float(self.similarity),
            "feedback": self.feedback,
            "ideal_answer": self.ideal_answer,
        }


class Embedder(Protocol):
    def encode(self, sentences: Sequence[str]) -> Any: ...


def cosine_similarity(a: np.ndarray, b: np.ndarray) -> float:
    a = np.asarray(a, dtype=float)
    b = np.asarray(b, dtype=float)
    denom = (np.linalg.norm(a) * np.linalg.norm(b)) + 1e-12
    return float(np.dot(a, b) / denom)


def similarity_to_score(sim: float) -> int:
    """
    Map cosine similarity (roughly 0..1) to a human-friendly 0..100 score.
    We clamp to avoid negative scores.
    """
    sim = float(sim)
    sim = max(0.0, min(sim, 1.0))
    return int(round(sim * 100))


def feedback_from_score(score: int) -> str:
    if score >= 80:
        return "Strong answer. Clear and aligned with the expected points."
    if score >= 60:
        return "Good answer. Consider adding more depth, examples, and trade-offs."
    if score >= 40:
        return "Partial answer. Add structure (problem → approach → result) and key technical details."
    return "Weak answer. Focus on fundamentals and give a concrete example aligned to the question."


def evaluate_answer(
    question: str,
    candidate_answer: str,
    ideal_answer: str,
    *,
    embedder: Embedder,
) -> EvaluationResult:
    q = (question or "").strip()
    cand = (candidate_answer or "").strip()
    ideal = (ideal_answer or "").strip()

    if not cand:
        return EvaluationResult(
            score=0,
            similarity=0.0,
            feedback="No answer provided.",
            ideal_answer=ideal,
        )

    # Include the question context in embeddings for slightly better alignment.
    cand_vec, ideal_vec = embedder.encode([f"Q: {q}\nA: {cand}", f"Q: {q}\nA: {ideal}"])
    sim = cosine_similarity(cand_vec, ideal_vec)
    score = similarity_to_score(sim)
    fb = feedback_from_score(score)
    return EvaluationResult(score=score, similarity=sim, feedback=fb, ideal_answer=ideal)


def evaluate_answer_tfidf(
    question: str,
    candidate_answer: str,
    ideal_answer: str,
) -> EvaluationResult:
    """
    Safe fallback evaluator that does NOT require torch/sentence-transformers.
    Uses TF-IDF cosine similarity between candidate and ideal answers.
    """
    q = (question or "").strip()
    cand = (candidate_answer or "").strip()
    ideal = (ideal_answer or "").strip()

    if not cand:
        return EvaluationResult(
            score=0,
            similarity=0.0,
            feedback="No answer provided.",
            ideal_answer=ideal,
        )
    if not ideal:
        # If we don't have an ideal answer, just grade based on answer completeness.
        score = 20 if len(cand) > 40 else 10
        return EvaluationResult(
            score=score,
            similarity=0.0,
            feedback="No ideal answer available. Score is based on answer length only.",
            ideal_answer=ideal,
        )

    vec = TfidfVectorizer(stop_words="english", ngram_range=(1, 2), min_df=1)
    X = vec.fit_transform([f"Q: {q}\nA: {cand}", f"Q: {q}\nA: {ideal}"]).toarray()
    sim = cosine_similarity(X[0], X[1])
    score = similarity_to_score(sim)
    fb = feedback_from_score(score)
    return EvaluationResult(score=score, similarity=sim, feedback=fb, ideal_answer=ideal)


def evaluate_batch_tfidf(
    questions: Sequence[str],
    candidate_answers: Sequence[str],
    ideal_answers: Sequence[str],
) -> List[Dict[str, Any]]:
    if not (len(questions) == len(candidate_answers) == len(ideal_answers)):
        raise ValueError("questions, candidate_answers, ideal_answers must have the same length.")

    out: List[Dict[str, Any]] = []
    for q, a, ideal in zip(questions, candidate_answers, ideal_answers):
        out.append(evaluate_answer_tfidf(q, a, ideal).to_dict())
    return out


def evaluate_batch(
    questions: Sequence[str],
    candidate_answers: Sequence[str],
    ideal_answers: Sequence[str],
    *,
    embedder: Embedder,
) -> List[Dict[str, Any]]:
    if not (len(questions) == len(candidate_answers) == len(ideal_answers)):
        raise ValueError("questions, candidate_answers, ideal_answers must have the same length.")

    out: List[Dict[str, Any]] = []
    for q, a, ideal in zip(questions, candidate_answers, ideal_answers):
        out.append(evaluate_answer(q, a, ideal, embedder=embedder).to_dict())
    return out

